testing better prettier report

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -150,7 +150,15 @@ jobs:
         with:
           node-version: 18.x
       - name: Check with Prettier
-        run: npx prettier --check --ignore-path .prettierignore '**/*.(yml|js|ts|json)'
+        run: |
+          npx prettier --ignore-path .prettierignore '**/*.(yml|js|ts|json)' \
+          || (git diff --quiet \
+          || (echo 'Unable to show a diff because there are unstaged changes'; false) \
+          && (npx prettier --ignore-path \
+              .prettierignore '**/*.(yml|js|ts|json)' -w --loglevel silent \
+          && git --no-pager diff; git restore .) && false)
+
+          npx prettier --check --ignore-path .prettierignore '**/*.(yml|js|ts|json)'
 
   check-cargo-toml-format:
     name: "Check Cargo.toml files format"
