Add build for features

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,6 +19,7 @@ on:
 env:
   SCCACHE_CACHE_SIZE: "100GB"
   CARGO_INCREMENTAL: "0"
+  RUSTC_WRAPPER: "sccache"
 
 jobs:
   ####### Check files and formatting #######
@@ -260,7 +261,6 @@ jobs:
     needs: ["set-tags"]
     env:
       RUSTFLAGS: "-C opt-level=3 -D warnings"
-      RUSTC_WRAPPER: "sccache"
       TMP_TARGET: "/tmp/target"
       CARGO_TARGET_DIR: "target"
     steps:
@@ -281,8 +281,6 @@ jobs:
       - name: Build Node
         run: |
           env
-          rustup show
-          rustc --version
           cargo build --release --all
       - name: Run sccache stat for check pre test
         shell: bash
@@ -312,13 +310,79 @@ jobs:
           name: moonbeam
           path: build
 
-  rust-test:
+  build-features:
     runs-on:
       labels: bare-metal
     needs: ["set-tags"]
     env:
       RUSTFLAGS: "-C opt-level=3 -D warnings"
-      RUSTC_WRAPPER: "sccache"
+      TMP_TARGET: "/tmp/target-features"
+      CARGO_TARGET_DIR: "target-features"
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ needs.set-tags.outputs.git_ref }}
+      - name: Run sccache-cache
+        uses: mozilla-actions/sccache-action@v0.0.3
+      # With rustup's nice new toml format, we just need to run rustup show to install the toolchain
+      # https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659
+      - name: Setup Rust toolchain
+        run: |
+          if ! which "rustup" > /dev/null; then
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+          fi
+          rustup show
+      - name: Build Node
+        run: |
+          env
+          cargo build --release --features=try-runtime,runtime-benchmarks,evm-tracing
+      - name: Run sccache stat for check pre test
+        shell: bash
+        run: ${SCCACHE_PATH} --show-stats
+      - name: Verify node version
+        run: |
+          GIT_COMMIT=`git log -1 --format="%H" | cut -c1-7`
+          MB_VERSION=`./$CARGO_TARGET_DIR/release/moonbeam --version`
+          echo "Checking $MB_VERSION contains $GIT_COMMIT"
+          echo "$MB_VERSION" | grep $GIT_COMMIT
+      - name: Check Cargo Toml
+        # We determine whether there are unmodified Cargo.lock files by:
+        # 1. Asking git for a list of all modified files
+        # 2. Using grep to reduce the list to only Cargo.lock files
+        # 3. Counting the number of lines of output
+        run: |
+          # Make sure git is working, and if not abort early. When git is not working it looks like:
+          # $ git diff-index --name-only HEAD
+          # fatal: not a git repository (or any of the parent directories): .git
+          DIFF_INDEX=$(git diff-index --name-only HEAD)
+          if [[ ${DIFF_INDEX:0:5} == "fatal" ]]; then
+            echo "There was an error with the git checkout. Can't check Cargo.lock file."
+            false
+          fi
+          FILECOUNT=$(echo $DIFF_INDEX | grep Cargo.lock | wc -l)
+          if [[ $FILECOUNT -eq 0 ]]; then
+            echo "All lock files are valid"
+          else
+            echo "The following Cargo.lock files have uncommitted changes"
+            echo $DIFF_INDEX | grep Cargo.lock
+            false
+          fi
+      - name: Save moonbeam binary
+        run: |
+          mkdir -p build
+          cp $CARGO_TARGET_DIR/release/moonbeam build/moonbeam-features;
+      - name: Upload binary
+        uses: actions/upload-artifact@v3.1.2
+        with:
+          name: moonbeam
+          path: build
+
+  rust-test:
+    runs-on:
+      labels: bare-metal
+    needs: ["set-tags"]
+    env:
       TMP_TARGET: "/tmp/target-test"
       CARGO_TARGET_DIR: "target-test"
     steps:
@@ -343,31 +407,6 @@ jobs:
       - name: Run sccache stat for check pre test
         shell: bash
         run: ${SCCACHE_PATH} --show-stats
-
-      # We determine whether there are unmodified Cargo.lock files by:
-      # 1. Asking git for a list of all modified files
-      # 2. Using grep to reduce the list to only Cargo.lock files
-      # 3. Counting the number of lines of output
-      - name: Check Cargo Toml
-        run: |
-          # Make sure git is working, and if not abort early. When git is not working it looks like:
-          # $ git diff-index --name-only HEAD
-          # fatal: not a git repository (or any of the parent directories): .git
-          DIFF_INDEX=$(git diff-index --name-only HEAD)
-          if [[ ${DIFF_INDEX:0:5} == "fatal" ]]; then
-            echo "There was an error with the git checkout. Can't check Cargo.lock file."
-            false
-          fi
-          FILECOUNT=$(echo $DIFF_INDEX | grep Cargo.lock | wc -l)
-          if [[ $FILECOUNT -eq 0 ]]; then
-            echo "All lock files are valid"
-          else
-            echo "The following Cargo.lock files have uncommitted changes"
-            echo $DIFF_INDEX | grep Cargo.lock
-            false
-          fi
-      - name: Ensure benchmarking compiles
-        run: cargo check --release --features=runtime-benchmarks
 
   typescript-tests:
     runs-on:
