support invalid coverage file :(

diff --git a/.github/workflows/coverage.yml b/.github/workflows/coverage.yml
--- a/.github/workflows/coverage.yml
+++ b/.github/workflows/coverage.yml
@@ -187,7 +187,29 @@ jobs:
           mkdir -p /tmp/proffiles
           find . -name \*.profraw -exec cp {} /tmp/proffiles \;
           mv /tmp/proffiles proffiles
-          ./grcov proffiles/ -s ./ --binary-path ./$CARGO_TARGET_DIR/release/ -t html --branch --ignore-not-existing -o coverage/ --llvm-path ./  --llvm
+          ./grcov proffiles/ -s ./ --binary-path ./$CARGO_TARGET_DIR/release/ \
+            -t html --branch --ignore-not-existing \
+            -o coverage/ --llvm-path ./  --llvm 2>&1 \
+            | tee grcov.log
+
+          // 
+          // llvm-profdata merge can fail for some reports (not sure why)
+          // so we remove them and retry
+
+          INVALID="$(grep invalid result.log | \
+            grep -o '[^\ /]*raw' | \
+            sed 's/_1\.profraw/\.profraw/g' || echo '')"
+
+          if [ -n "$INVALID" ]; then
+            echo "Removing invalid files: $INVALID"
+            cd proffiles/
+            rm $INVALID
+            cd ..
+            ./grcov proffiles/ -s ./ --binary-path ./$CARGO_TARGET_DIR/release/ \
+            -t html --branch --ignore-not-existing \
+            -o coverage/ --llvm-path ./  --llvm
+          fi
+
       - name: Upload coverage
         uses: actions/upload-artifact@v3.1.2
         with:
